apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qrcode-generator
spec:
  selector:
    app: {{ .Release.Name }}-qrcode-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.application.service.type }}
