apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-connection-test
spec:
  selector:
    app: {{ .Release.Name }}-db-connection-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.application.service.type }}
