apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-movies-series
  annotations:  
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- if .Values.application.ingress.sslRedirect.enabled }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}  
spec:
  {{- if .Values.application.ingress.ingressClassName }}
  ingressClassName: {{ .Values.application.ingress.ingressClassName }}
  {{- end }}

  {{- if .Values.application.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Release.Name }}-movies-series-tls
      hosts:
      {{- range .Values.application.ingress.hosts }}
        - {{ . }}
      {{- end }}
  {{- end }}
  rules:
  {{- range .Values.application.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-movies-series-service
                port:
                  number: 80
  {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-movies-series-db
spec:
  rules:
    - host: movies-db.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgre-{{ .Release.Name }}-movies-series-service
                port:
                  number: 5432