apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-movies-series
spec:
  rules:
  {{- range .Values.application.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-movies-series-service
                port:
                  number: 80
  {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-movies-series-db
spec:
  rules:
    - host: movies-db.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgre-{{ .Release.Name }}-movies-series-service
                port:
                  number: 5432