apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movies-series-service
spec:
  selector:
    app: {{ .Release.Name }}-movies-series
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: {{ .Values.application.service.type }}
  
---

apiVersion: v1
kind: Service
metadata:
  name: postgre-{{ .Release.Name }}-movies-series-service
spec:
  selector:
    app: postgre-{{ .Release.Name }}-movies-series
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432