application:
  replicas: 1
  image:
    name: felipecs8/conversor-temperatura
    tag: v1
  service:
    type: ClusterIP
  clusterIssuer: "letsencrypt-prod"
  ingress:
    hosts:
    - conversor-temp.127.0.0.1.nip.io
    ingressClassName: null
    tls:
      enabled: false
    sslRedirect:
      enabled: false