apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-qrcode-generator-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  {{- if .Values.application.ingress.ingressClassName }}
  ingressClassName: {{ .Values.application.ingress.ingressClassName }}
  {{- end }}

  {{- if .Values.application.ingress.tls.enabled }}
  tls:
  {{- range .Values.application.ingress.hosts }}
    - hosts:
        - {{ . }}
      secretName: web-qrcode-generator-tls
  {{- end }}
  {{- end }}

  rules:
  {{- range .Values.application.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-qrcode-generator
                port:
                  number: 80
  {{- end }}
