apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-conversor-temperatura-helm
spec:
  selector:
    app: {{ .Release.Name }}-conversor-temperatura-helm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.application.service.type }}
